chore: rename `config` folder to `static`

diff --git a/apps/elearning/bin/prepare b/apps/elearning/bin/prepare
--- a/apps/elearning/bin/prepare
+++ b/apps/elearning/bin/prepare
@@ -1,4 +1,14 @@
 #!/usr/bin/env sh
 
+R="\033[0;31m"
+
+[ -f .env ] && . .env
+
+if [ -z "$SUPABASE_ACCESS_TOKEN" ]; then
+  echo "${R}Error: SUPABASE_ACCESS_TOKEN must be set"
+  exit 1
+fi
+
+pnpm dlx supabase login --token "$SUPABASE_ACCESS_TOKEN" >/dev/null
 pnpm dlx supabase init --force --with-intellij-settings=false --with-vscode-settings=false
 pnpm typegen
