ci: fix typegen in ci environments

diff --git a/apps/elearning/bin/typegen b/apps/elearning/bin/typegen
--- a/apps/elearning/bin/typegen
+++ b/apps/elearning/bin/typegen
@@ -1,6 +1,23 @@
 #!/usr/bin/env sh
 
+R="\033[0;31m"
+
 SCHEMA=auth,public,storage
 TYPES=supabase/types.ts
+root=$(git rev-parse --show-toplevel)
+arg="--local"
 
-./node_modules/.bin/supabase gen types typescript --schema=$SCHEMA --local > $TYPES
+[ -f "$root/.env" ] && . "$root/.env"
+
+if [ -z "$SUPABASE_PROJECT_ID" ]; then
+  echo "${R}Error: SUPABASE_PROJECT_ID is not set"
+  exit 1
+fi
+
+if [ "$ENV" = "production" ] || [ "$NODE_ENV" = "production" ] || [ "$GITHUB_ACTIONS" = "true" ] || [ "$CI" = "true" ] || [ "$CI" = 1 ]; then
+  arg="--project-id=$SUPABASE_PROJECT_ID"
+fi
+
+if ./node_modules/.bin/supabase gen types typescript --schema=$SCHEMA "$arg" > $TYPES; then
+  echo "Finished types generation."
+fi
