chore(dev): set up seeds

diff --git a/apps/elearning/.bin/prepare b/apps/elearning/.bin/prepare
--- a/apps/elearning/.bin/prepare
+++ b/apps/elearning/.bin/prepare
@@ -1,14 +1,20 @@
 #!/usr/bin/env sh
 
-R="\033[0;31m"
-
 [ -f .env ] && . ./.env
 
 if [ -z "$SUPABASE_ACCESS_TOKEN" ] || [ -z "$SUPABASE_PROJECT_ID" ] || [ -z "$SUPABASE_DB_PASSWORD" ]; then
-  echo "${R}Error: missing Supabase environment variables"
+  echo "Missing Supabase environment variables."
   exit 1
 fi
 
 ./node_modules/.bin/supabase login --token "$SUPABASE_ACCESS_TOKEN" >/dev/null
 ./node_modules/.bin/supabase link --project-ref "$SUPABASE_PROJECT_ID" --password "$SUPABASE_DB_PASSWORD" >/dev/null 2>&1
-sh ./bin/typegen
+sh ./.bin/typegen
+exit=$?
+
+if [ "$ENV" = "production" ] || [ "$NODE_ENV" = "production" ] || [ "$GITHUB_ACTIONS" = "true" ] || [ "$CI" = "true" ] || [ "$CI" = 1 ]; then
+  exit $exit
+fi
+
+./node_modules/.bin/supabase start >/dev/null 2>&1
+./node_modules/.bin/snaplet-seed init supabase >/dev/null 2>&1
