feat: Add custom mailer for auth and transactional emails

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,6 +1,9 @@
 name: CI
 
 on:
+  push:
+    branches:
+      - main
   pull_request:
     branches:
       - main
@@ -8,24 +11,20 @@ on:
       - opened
       - reopened
       - synchronize
-  workflow_dispatch:
   merge_group:
     types:
       - checks_requested
 
 env:
+  SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
   SUPABASE_TOKEN: ${{ secrets.SUPABASE_TOKEN }}
   TURBO_TEAM: ${{ vars.TURBO_TEAM }}
   TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
-  NEXT_TELEMETRY_DISABLED: 1
-  TURBO_TELEMETRY_DISABLED: 1
 
 jobs:
   code-checks:
     name: Code checks
     runs-on: ubuntu-latest
-    env:
-      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL_PREVIEW }}
     permissions:
       checks: write
       contents: read
@@ -34,5 +33,18 @@ jobs:
       - uses: actions/checkout@v5
       - name: Set up environment
         uses: ./.github/actions/setup
-      - name: Run code checks
-        uses: ./.github/actions/code-checks
+      - name: Run commitlint on push
+        if: github.event_name == 'push'
+        run: |
+          if ! commitlint --from ${{ github.event.before }} --to ${{ github.event.after }} --verbose; then
+            echo "::warning::Cannot execute commitlint on this range, running on last commit instead."
+            commitlint --last --verbose
+          fi
+      - name: Run commitlint on pull request
+        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
+        run: |
+          if ! commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose; then
+            echo "::warning::Cannot execute commitlint on this range, running on last commit instead."
+            commitlint --last --verbose
+          fi
+      - run: pnpm check
